### ISSUE TITLE
Following symbolic links causes an exception to be thrown

### ISSUE THREAD

**Issue by edwardUL99** [edwardUL99/simple-ftp#63]
If there is a symbolic link and it is a directory, opening it results in an Exception dialog to open with the following exception:

> com.simpleftp.filesystem.exceptions.FileSystemException: The directory for a FilePanel must be in fact a directory, not a file
	at com.simpleftp.ui.panels.FilePanel.setDirectory(FilePanel.java:389)
	at com.simpleftp.ui.panels.FilePanel.doubleClickDirectoryEntry(FilePanel.java:682)
	at com.simpleftp.ui.panels.FilePanel.doubleClick(FilePanel.java:730)
	at com.simpleftp.ui.panels.FilePanel.openLineEntry(FilePanel.java:755)

In the RemoteFile.exists method, you've added || ftpFile.isSymbolicLink(). See when checking if directory, if it is a symbolic link, try and determine if it is a directory by using FTPConnection.remotePathExists(path, true) to check for directory

Symbolic links may vary between servers, so in the future, they may be disallowed and not shown in the program at all

**Comment by edwardUL99** [comment]
Symbolic links aren't perfect, but they work for now. They can be improved upon later
